<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductVariant;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = Product::with(['category', 'images' => fn ($q) => $q->where('is_primary', true)])
            ->when($request->search, fn ($q) => $q->where('name', 'like', '%' . $request->search . '%'))
            ->when($request->category_id, fn ($q) => $q->where('category_id', $request->category_id))
            ->when($request->gender, fn ($q) => $q->where('gender', $request->gender))
            ->orderByDesc('id')
            ->paginate(10)
            ->withQueryString();

        $categories = Category::orderBy('name')->get(['id', 'name']);

        return view('admin.products.index', compact('products', 'categories'));
    }

    public function create()
    {
        $categories = Category::active()->orderBy('name')->get(['id', 'name']);

        return view('admin.products.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $this->nullifyBlankFields($request);
        $validated = $this->validateProduct($request);
        $hasVariants = $request->boolean('has_variants');

        $product = DB::transaction(function () use ($request, $validated, $hasVariants) {
            $product = Product::create([
                'category_id' => $validated['category_id'],
                'name' => $validated['name'],
                'sku' => $validated['sku'] ?? null,
                'gender' => $validated['gender'],
                'short_description' => $validated['short_description'] ?? null,
                'description' => $validated['description'] ?? null,
                'price' => $validated['price'] ?? 0,
                'discount_price' => $validated['discount_price'] ?? null,
                'stock' => $hasVariants ? 0 : ($validated['stock'] ?? 0),
                'has_variants' => $hasVariants,
                'weight' => $validated['weight'] ?? null,
                'is_featured' => $request->boolean('is_featured'),
                'is_active' => true,
            ]);
            // slug is auto-generated by Product::booted() 'creating' hook

            $this->syncVariants($product, $request);
            $this->storeImages($product, $request);

            if ($hasVariants) {
                $product->update([
                    'stock' => $product->variants()->sum('stock'),
                    // If no base price was entered, use the lowest variant price as the "from" price.
                    'price' => $validated['price'] ?? ($product->variants()->min('price') ?? 0),
                ]);
            }

            return $product;
        });

        return redirect()
            ->route('admin.products.index')
            ->with('success', "Product \"{$product->name}\" created successfully.");
    }

    public function edit(Product $product)
    {
        $product->load(['images', 'variants']);
        $categories = Category::active()->orderBy('name')->get(['id', 'name']);

        return view('admin.products.edit', compact('product', 'categories'));
    }

    public function update(Request $request, Product $product)
    {
        $this->nullifyBlankFields($request);
        $validated = $this->validateProduct($request, $product->id);
        $hasVariants = $request->boolean('has_variants');

        DB::transaction(function () use ($request, $product, $validated, $hasVariants) {
            $product->update([
                'category_id' => $validated['category_id'],
                'name' => $validated['name'],
                'sku' => $validated['sku'] ?? null,
                'gender' => $validated['gender'],
                'short_description' => $validated['short_description'] ?? null,
                'description' => $validated['description'] ?? null,
                'price' => $validated['price'] ?? $product->price,
                'discount_price' => $validated['discount_price'] ?? null,
                'stock' => $hasVariants ? 0 : ($validated['stock'] ?? 0),
                'has_variants' => $hasVariants,
                'weight' => $validated['weight'] ?? null,
                'is_featured' => $request->boolean('is_featured'),
                // slug intentionally left untouched to keep URLs/SEO stable
            ]);

            // Variant rows are fully re-submitted from the edit form, so replace wholesale.
            $product->variants()->delete();
            if ($hasVariants) {
                $this->syncVariants($product, $request);
                $product->update([
                    'stock' => $product->variants()->sum('stock'),
                    'price' => $validated['price'] ?? ($product->variants()->min('price') ?? $product->price),
                ]);
            }

            $this->storeImages($product, $request);
        });

        return redirect()
            ->route('admin.products.index')
            ->with('success', 'Product updated successfully.');
    }

    public function destroy(Product $product)
    {
        foreach ($product->images as $image) {
            Storage::disk('public')->delete($image->path);
        }

        ProductImage::where('product_id', $product->id)->delete();
        ProductVariant::where('product_id', $product->id)->delete();
        $product->delete(); // soft delete (SoftDeletes trait)

        return response()->json(['message' => 'Product deleted successfully.']);
    }

    public function toggleStatus(Product $product)
    {
        $product->update(['is_active' => !$product->is_active]);

        return response()->json([
            'message' => $product->is_active ? 'Product activated.' : 'Product deactivated.',
            'is_active' => $product->is_active,
        ]);
    }

    /**
     * AJAX: delete a single existing image from the Edit page.
     */
    public function destroyImage(ProductImage $image)
    {
        Storage::disk('public')->delete($image->path);
        $wasPrimary = $image->is_primary;
        $productId = $image->product_id;
        $image->delete();

        if ($wasPrimary) {
            $next = ProductImage::where('product_id', $productId)->orderBy('sort_order')->first();
            $next?->update(['is_primary' => true]);
        }

        return response()->json(['message' => 'Image removed.']);
    }

    // ── Helpers ──────────────────────────────────────────────

    private function validateProduct(Request $request, ?int $productId = null): array
    {
        $validator = Validator::make($request->all(), [
            'category_id' => ['required', 'exists:categories,id'],
            'name' => ['required', 'string', 'max:255'],
            'sku' => ['nullable', 'string', 'max:255', Rule::unique('products', 'sku')->ignore($productId)],
            'short_description' => ['nullable', 'string', 'max:500'],
            'description' => ['nullable', 'string'],
            'gender' => ['required', 'in:men,women,kids,unisex'],
            'has_variants' => ['nullable', 'boolean'],
            'price' => [Rule::requiredIf(!$request->boolean('has_variants')), 'nullable', 'numeric', 'min:0'],
            'discount_price' => ['nullable', 'numeric', 'min:0'],
            'stock' => ['nullable', 'integer', 'min:0'],
            'weight' => ['nullable', 'numeric', 'min:0'],
            'is_featured' => ['nullable', 'boolean'],
            'images.*' => ['nullable', 'image', 'max:4096'],
            'primary_image_index' => ['nullable', 'integer'],
            'variants' => ['nullable', 'array'],
            'variants.*.size' => ['nullable', 'string', 'max:50'],
            'variants.*.color' => ['nullable', 'string', 'max:50'],
            'variants.*.price' => ['nullable', 'numeric', 'min:0'],
            'variants.*.discount_price' => ['nullable', 'numeric', 'min:0'],
            'variants.*.stock' => ['nullable', 'integer', 'min:0'],
            'variants.*.sku' => ['nullable', 'string', 'max:100'],
        ]);

        $validator->after(function ($validator) use ($request) {
            if (!$request->boolean('has_variants')) {
                return;
            }

            $rows = $request->input('variants', []);
            $hasAnyPrice = collect($rows)->contains(
                fn ($row) => isset($row['price']) && $row['price'] !== '' && (float) $row['price'] > 0
            );

            if (!$hasAnyPrice) {
                $validator->errors()->add('variants', 'At least one variant must have a price greater than 0.');
            }
        });

        return $validator->validate();
    }

    private function syncVariants(Product $product, Request $request): void
    {
        if (!$request->boolean('has_variants') || !$request->has('variants')) {
            return;
        }

        $seenCombos = [];

        foreach ($request->input('variants', []) as $row) {
            $size = trim($row['size'] ?? '');
            $color = trim($row['color'] ?? '');

            if ($size === '' && $color === '') {
                continue; // skip fully empty rows
            }

            $comboKey = strtolower($size . '|' . $color);
            if (isset($seenCombos[$comboKey])) {
                continue; // skip duplicate size+color combos (DB has a unique constraint on this)
            }
            $seenCombos[$comboKey] = true;

            ProductVariant::create([
                'product_id' => $product->id,
                'size' => $size ?: null,
                'color' => $color ?: null,
                'price' => $row['price'] ?? null,
                'discount_price' => $row['discount_price'] ?? null,
                'stock' => $row['stock'] ?? 0,
                'sku' => ($row['sku'] ?? null) ?: $this->uniqueVariantSku(),
                'is_active' => true,
            ]);
        }
    }

    private function storeImages(Product $product, Request $request): void
    {
        if (!$request->hasFile('images')) {
            return;
        }

        $primaryIndex = (int) $request->input('primary_image_index', 0);
        $hasExistingPrimary = $product->images()->where('is_primary', true)->exists();
        $nextSort = (int) $product->images()->max('sort_order') + 1;

        foreach ($request->file('images') as $i => $file) {
            $path = $file->store('products', 'public');
            $isPrimary = !$hasExistingPrimary && $i === $primaryIndex;

            ProductImage::create([
                'product_id' => $product->id,
                'path' => $path,
                'color' => $request->input("image_colors.$i") ?: null,
                'is_primary' => $isPrimary,
                'sort_order' => $nextSort++,
            ]);

            if ($isPrimary) {
                $hasExistingPrimary = true;
            }
        }
    }

    private function uniqueVariantSku(): string
    {
        do {
            $sku = 'VAR-' . strtoupper(Str::random(8));
        } while (ProductVariant::where('sku', $sku)->exists());

        return $sku;
    }

    /**
     * Convert empty-string values to null for nullable+unique fields (sku),
     * so blank inputs don't collide against each other in the unique index.
     */
    private function nullifyBlankFields(Request $request): void
    {
        if ($request->input('sku') === '') {
            $request->merge(['sku' => null]);
        }
        if ($request->input('price') === '') {
            $request->merge(['price' => null]);
        }
        if ($request->input('discount_price') === '') {
            $request->merge(['discount_price' => null]);
        }
    }
}